# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P08_-_Multiplier_Pipeline/P08_-_Multiplier_Pipeline.srcs/sources_1/ip/Multiplier/Multiplier.xci
# IP: The module: 'Multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P08_-_Multiplier_Pipeline/P08_-_Multiplier_Pipeline.gen/sources_1/ip/Multiplier/Multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Multiplier'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P08_-_Multiplier_Pipeline/P08_-_Multiplier_Pipeline.srcs/sources_1/ip/Multiplier/Multiplier.xci
# IP: The module: 'Multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P08_-_Multiplier_Pipeline/P08_-_Multiplier_Pipeline.gen/sources_1/ip/Multiplier/Multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
