# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/T02_-_PC_PO_HLS/PC-PO/PC-PO-VHDL/PC-PO-VHDL.srcs/sources_1/ip/mem_r/mem_r.xci
# IP: The module: 'mem_r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/T02_-_PC_PO_HLS/PC-PO/PC-PO-VHDL/PC-PO-VHDL.gen/sources_1/ip/mem_r/mem_r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_r'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/T02_-_PC_PO_HLS/PC-PO/PC-PO-VHDL/PC-PO-VHDL.srcs/sources_1/ip/mem_r/mem_r.xci
# IP: The module: 'mem_r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/T02_-_PC_PO_HLS/PC-PO/PC-PO-VHDL/PC-PO-VHDL.gen/sources_1/ip/mem_r/mem_r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
