#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_0_0", 8, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("a_0_1", 8, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("a_1_0", 8, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("a_1_1", 8, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("b_0_0", 8, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("b_0_1", 8, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("b_1_0", 8, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("b_1_1", 8, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("c_0_0", 16, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("c_0_1", 16, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("c_1_0", 16, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("c_1_1", 16, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("result_0_0", 8, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("result_0_0_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
	Port_Property("result_0_1", 8, hls_out, 13, "ap_vld", "out_data", 1),
	Port_Property("result_0_1_ap_vld", 1, hls_out, 13, "ap_vld", "out_vld", 1),
	Port_Property("result_1_0", 8, hls_out, 14, "ap_vld", "out_data", 1),
	Port_Property("result_1_0_ap_vld", 1, hls_out, 14, "ap_vld", "out_vld", 1),
	Port_Property("result_1_1", 8, hls_out, 15, "ap_vld", "out_data", 1),
	Port_Property("result_1_1_ap_vld", 1, hls_out, 15, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "calculate_matrix";
