# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P07_-_Memory_FSM/P07_-_Memory_FSM.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P07_-_Memory_FSM/P07_-_Memory_FSM.gen/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P07_-_Memory_FSM/P07_-_Memory_FSM.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pllima0909/Documents/Git/INF01175-Digital-Systems/P07_-_Memory_FSM/P07_-_Memory_FSM.gen/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
